### ISSUE TITLE
'com.vertica.jdbc.Driver' does not denote a valid java.sql.Driver class name

### ISSUE THREAD

**Issue by SvenC56** [luciodaza/dremio-vertica-connector#3]
Hey,

I'm on version `4.2.0` and I tried install this plugin. However on creation of the datasource I get this error message:

```
2020-06-29 20:37:05,475 [start-Vertica] WARN  c.d.e.catalog.ManagedStoragePlugin - Error starting new source: Vertica
java.lang.IllegalArgumentException: String 'com.vertica.jdbc.Driver' does not denote a valid java.sql.Driver class name.
	at com.dremio.exec.store.jdbc.DataSources.newGenericConnectionPoolDataSource(DataSources.java:60)
	at com.dremio.exec.store.jdbc.conf.VerticaConf.newDataSource(VerticaConf.java:105)
	at com.dremio.exec.store.jdbc.JdbcStoragePlugin.start(JdbcStoragePlugin.java:387)
	at com.dremio.exec.catalog.ManagedStoragePlugin.lambda$newStartSupplier$2(ManagedStoragePlugin.java:490)
	at com.dremio.exec.catalog.ManagedStoragePlugin.lambda$nameSupplier$4(ManagedStoragePlugin.java:554)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.vertica.jdbc.Driver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.dremio.exec.store.jdbc.DataSources.newGenericConnectionPoolDataSource(DataSources.java:58)
	... 8 common frames omitted
2020-06-29 20:37:05,476 [qtp1007042810-106] ERROR c.d.e.store.jdbc.JdbcStoragePlugin - Connection is not valid.
java.lang.NullPointerException: null
	at com.dremio.exec.store.jdbc.JdbcStoragePlugin.getState(JdbcStoragePlugin.java:360)
	at com.dremio.exec.catalog.ManagedStoragePlugin.setLocals(ManagedStoragePlugin.java:782)
	at com.dremio.exec.catalog.ManagedStoragePlugin.replacePlugin(ManagedStoragePlugin.java:894)
	at com.dremio.exec.catalog.ManagedStoragePlugin.createOrUpdateSource(ManagedStoragePlugin.java:331)
	at com.dremio.exec.catalog.ManagedStoragePlugin.createSource(ManagedStoragePlugin.java:297)
	at com.dremio.exec.catalog.PluginsManager.create(PluginsManager.java:165)
	at com.dremio.exec.catalog.CatalogServiceImpl.createSource(CatalogServiceImpl.java:364)
	at com.dremio.exec.catalog.CatalogServiceImpl.access$400(CatalogServiceImpl.java:98)
	at com.dremio.exec.catalog.CatalogServiceImpl$SourceModifier.createSource(CatalogServiceImpl.java:606)
	at com.dremio.exec.catalog.CatalogImpl.createSource(CatalogImpl.java:720)
	at com.dremio.exec.catalog.SourceAccessChecker.createSource(SourceAccessChecker.java:282)
	at com.dremio.exec.catalog.DelegatingCatalog.createSource(DelegatingCatalog.java:240)
	at com.dremio.dac.service.source.SourceService.registerSourceWithRuntime(SourceService.java:161)
	at com.dremio.dac.service.source.SourceService.registerSourceWithRuntime(SourceService.java:152)
	at com.dremio.dac.service.source.SourceService.registerSourceWithRuntime(SourceService.java:148)
	at com.dremio.dac.resource.PutSourceResource.putSource(PutSourceResource.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1617)
	at com.dremio.dac.server.tracing.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:46)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at com.dremio.dac.server.SecurityHeadersFilter.doFilter(SecurityHeadersFilter.java:52)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:717)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)
```

I ran `mvn clean install` and copied the `.jar` into my Dockerfile like:

```Dockerfile
FROM dremio/dremio-oss:4.2.0

ENV DREMIO_HOME /opt/dremio
ENV DREMIO_PID_DIR /var/run/dremio
ENV DREMIO_GC_LOGS_ENABLED="no"
ENV DREMIO_LOG_DIR="/var/log/dremio"
ENV SERVER_GC_OPTS="-XX:+PrintGCDetails -XX:+PrintGCDateStamps"

COPY ./vertica/dremio-verticaarp-plugin-4.2.jar ${DREMIO_HOME}/jars/dremio-verticaarp-plugin-4.2.jar
COPY ./salesforce/cdata.jdbc.salesforce.jar ${DREMIO_HOME}/jars/3rdparty/cdata.jdbc.salesforce.jar
COPY ./salesforce/cdata.jdbc.salesforce.lic ${DREMIO_HOME}/jars/3rdparty/cdata.jdbc.salesforce.lic

EXPOSE 9047/tcp
EXPOSE 31010/tcp
EXPOSE 45678/tcp

ENTRYPOINT ["bin/dremio", "start-fg"]
```

**Comment by SvenC56** [comment]
I was able to solve this issue by adding the Vertica JDBC driver to the container. However this is not documented.

```Dockerfile
FROM dremio/dremio-oss:4.2.0

ENV DREMIO_HOME /opt/dremio
ENV DREMIO_PID_DIR /var/run/dremio
ENV DREMIO_GC_LOGS_ENABLED="no"
ENV DREMIO_LOG_DIR="/var/log/dremio"
ENV SERVER_GC_OPTS="-XX:+PrintGCDetails -XX:+PrintGCDateStamps"

USER dremio
WORKDIR ${DREMIO_HOME}

COPY --chown=1000:1000 ./vertica/dremio-verticaarp-plugin-4.2.jar ${DREMIO_HOME}/jars/dremio-verticaarp-plugin-4.2.jar
COPY --chown=1000:1000 ./vertica/vertica-jdbc-10.0.0-0.jar ${DREMIO_HOME}/jars/3rdparty/vertica-jdbc-10.0.0-0.jar
COPY --chown=1000:1000 ./salesforce/cdata.jdbc.salesforce.jar ${DREMIO_HOME}/jars/3rdparty/cdata.jdbc.salesforce.jar
COPY --chown=1000:1000 ./salesforce/cdata.jdbc.salesforce.lic ${DREMIO_HOME}/jars/3rdparty/cdata.jdbc.salesforce.lic

EXPOSE 9047/tcp
EXPOSE 31010/tcp
EXPOSE 45678/tcp

ENTRYPOINT ["bin/dremio", "start-fg"]
```
